title: LJZN
description: Everything about Ruby.
author: LJZN
github: https://github.com/ljzn
about: Currently doing more in backend, actually in Ruby and Rails.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/ljzn
url: "https://ljzn.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
