title: LJZN
description: Everything about Ruby.
author: LJZN
github: https://github.com/ljzn
about: It's me.
urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/ljzn
url: "https://ljzn.github.io"
baseurl: ""
paginate: 7
per_page: 7
paginate_path: "/page:num/"
markdown: kramdown
text-color: black
